# Generated by Django 2.2.2 on 2019-06-24 08:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club_mgt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('contents', djrichtextfield.models.RichTextField(verbose_name='內文')),
                ('due', models.DateTimeField(default=datetime.datetime(2019, 8, 23, 23, 59, 59, 999999), verbose_name='到期日')),
                ('log_add_time', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='發布人')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_mgt.Club', verbose_name='社團')),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': (('can_view', 'Can view Announcement'), ('can_add', 'Can add Announcement'), ('can_edit', 'Can edit Announcement'), ('can_close', 'Can close Announcement'), ('can_delete', 'Can delete Announcement')),
            },
        ),
    ]
